# Generated by Django 4.2.24 on 2025-10-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='Explicação da Resposta Correta'),
        ),
    ]
